import { Product, ProductVariant, Order, Supplier } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Baby Cotton Bodysuit',
    description: 'Soft cotton bodysuit perfect for newborns. Made with 100% organic cotton for sensitive skin.',
    category: 'Bodysuits',
    retail_price: 12000,
    wholesale_price: 8000,
    images: ['https://images.pexels.com/photos/1257110/pexels-photo-1257110.jpeg'],
  },
  {
    id: '2',
    name: 'Kids Striped Pajamas',
    description: 'Comfortable striped pajamas for kids. Breathable fabric for a good night sleep.',
    category: 'Sleepwear',
    retail_price: 18000,
    wholesale_price: 12000,
    images: ['https://images.pexels.com/photos/8088495/pexels-photo-8088495.jpeg'],
  },
  {
    id: '3',
    name: 'Baby Summer Dress',
    description: 'Adorable summer dress with floral patterns. Perfect for warm weather.',
    category: 'Dresses',
    retail_price: 22000,
    wholesale_price: 15000,
    images: ['https://images.pexels.com/photos/6393342/pexels-photo-6393342.jpeg'],
  },
  {
    id: '4',
    name: 'Toddler T-Shirt Set',
    description: 'Pack of 3 colorful t-shirts for toddlers. Soft and durable fabric.',
    category: 'T-Shirts',
    retail_price: 25000,
    wholesale_price: 17000,
    images: ['https://images.pexels.com/photos/8088508/pexels-photo-8088508.jpeg'],
  },
  {
    id: '5',
    name: 'Baby Knit Sweater',
    description: 'Warm knit sweater for babies. Perfect for cold weather.',
    category: 'Sweaters',
    retail_price: 28000,
    wholesale_price: 19000,
    images: ['https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg'],
  },
  {
    id: '6',
    name: 'Kids Denim Jeans',
    description: 'Comfortable denim jeans for kids. Adjustable waist for perfect fit.',
    category: 'Pants',
    retail_price: 30000,
    wholesale_price: 20000,
    images: ['https://images.pexels.com/photos/8088501/pexels-photo-8088501.jpeg'],
  },
  {
    id: '7',
    name: 'Baby Romper Set',
    description: 'Cute romper with matching hat. Ideal for photoshoots.',
    category: 'Rompers',
    retail_price: 20000,
    wholesale_price: 13000,
    images: ['https://images.pexels.com/photos/8088489/pexels-photo-8088489.jpeg'],
  },
  {
    id: '8',
    name: 'Toddler Hoodie',
    description: 'Soft fleece hoodie for toddlers. Keeps them warm and cozy.',
    category: 'Hoodies',
    retail_price: 26000,
    wholesale_price: 18000,
    images: ['https://images.pexels.com/photos/8088506/pexels-photo-8088506.jpeg'],
  },
];

export const mockVariants: ProductVariant[] = [
  { id: 'v1', product_id: '1', size: 'NB', color: 'White', stock: 10 },
  { id: 'v2', product_id: '1', size: '3M', color: 'White', stock: 8 },
  { id: 'v3', product_id: '1', size: '6M', color: 'Pink', stock: 3 },
  { id: 'v4', product_id: '2', size: '2T', color: 'Blue', stock: 15 },
  { id: 'v5', product_id: '2', size: '3T', color: 'Blue', stock: 12 },
  { id: 'v6', product_id: '3', size: '12M', color: 'Pink', stock: 7 },
  { id: 'v7', product_id: '3', size: '18M', color: 'Yellow', stock: 5 },
  { id: 'v8', product_id: '4', size: '2T', color: 'Mixed', stock: 20 },
  { id: 'v9', product_id: '4', size: '3T', color: 'Mixed', stock: 18 },
  { id: 'v10', product_id: '5', size: '6M', color: 'Beige', stock: 6 },
  { id: 'v11', product_id: '5', size: '12M', color: 'Beige', stock: 4 },
  { id: 'v12', product_id: '6', size: '4T', color: 'Blue', stock: 14 },
  { id: 'v13', product_id: '6', size: '5T', color: 'Black', stock: 10 },
  { id: 'v14', product_id: '7', size: '3M', color: 'White', stock: 9 },
  { id: 'v15', product_id: '7', size: '6M', color: 'Pink', stock: 2 },
  { id: 'v16', product_id: '8', size: '2T', color: 'Gray', stock: 11 },
  { id: 'v17', product_id: '8', size: '3T', color: 'Navy', stock: 13 },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    order_number: '1001',
    customer_phone: '+573001234567',
    total_price: 50000,
    status: 'pending',
    created_at: '2024-03-10T10:30:00',
    items: [],
  },
  {
    id: 'o2',
    order_number: '1002',
    customer_phone: '+573007654321',
    total_price: 75000,
    status: 'confirmed',
    created_at: '2024-03-09T15:45:00',
    items: [],
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 's1',
    name: 'Cotton Imports Co.',
    phone: '+573101234567',
    email: 'contact@cottonimports.com',
    address: 'Calle 123 #45-67, Bogotá',
    notes: 'Main supplier for cotton fabrics',
  },
  {
    id: 's2',
    name: 'Baby Textiles Ltd.',
    phone: '+573109876543',
    email: 'info@babytextiles.com',
    address: 'Carrera 50 #23-45, Medellín',
    notes: 'Specialized in baby clothing',
  },
];
